name: ❖ CI

on:
  workflow_call:
permissions:
  contents: read
  id-token: write

jobs:
  check-rs:
    name: Check Rust Code
    uses: ./.github/workflows/sub-rs-check.yaml
    secrets: inherit

  build-rs:
    name: Build Rust Project
    uses: ./.github/workflows/sub-rs-build.yaml
    secrets: inherit
